'use client'

import React from 'react'
import { VideoCard as VideoCardType } from '@/hooks/video-gallery/useVideoGallery'
import ProcessingVideoCard from './ProcessingVideoCard'

interface VideoCardProps {
  video: VideoCardType
  onViewVideo: (video: VideoCardType) => void
  onPostVideo: (video: VideoCardType) => void
}

export default function VideoCard({ video, onViewVideo, onPostVideo }: VideoCardProps) {
  const isProcessing = video.id.startsWith('loading-')

  return (
    <div className="bg-[#EEEEEE] rounded-[12px] overflow-hidden transition-all duration-300 group min-h-[200px]">
      {/* Video Player Container */}
      <div className="relative aspect-video max-h-[200px] w-full bg-[#EEEEEE] px-3 pt-3 rounded-[8px] group">
        {video.status === 'ready' && video.downloadUrl ? (
          <>
            <video
              src={video.downloadUrl}
              className="w-full h-[200px] object-cover rounded-[6px]"
              preload="metadata"
              poster=""
              muted
              loop
              playsInline
              webkit-playsinline="true"
              onError={(e) => console.error('Video load error:', e)}
              onLoadedMetadata={(e) => {
                const videoElement = e.currentTarget
                if (videoElement) {
                  videoElement.currentTime = 1
                }
              }}
            >
              Your browser does not support the video tag.
            </video>
            {/* View Video Button Overlay - Only visible on hover */}
            <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-grey100 bg-opacity-30 rounded-[6px]">
              <button
                onClick={() => onViewVideo(video)}
                className="bg-[#5046E5] text-white px-6 py-3 rounded-full font-semibold text-[16px] hover:bg-[#4338CA] transition-colors duration-300 flex items-center justify-center gap-2 shadow-lg"
              >
                View Video
              </button>
            </div>
          </>
        ) : isProcessing ? (
          <ProcessingVideoCard />
        ) : (
          <div className="w-full h-[200px] bg-gradient-to-br from-gray-200 to-gray-300 flex items-center justify-center rounded-[6px]">
            <div className="text-center">
              <div className="text-gray-400 text-sm mb-2">
                {video.status === 'processing' ? 'Processing...' :
                  video.status === 'failed' ? 'Failed to load' :
                    video.status === 'ready' && !video.downloadUrl ? 'No download URL' : 'Video not ready'}
              </div>
              {video.status === 'processing' && (
                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-[#5046E5] mx-auto"></div>
              )}
              {video.status === 'ready' && !video.downloadUrl && (
                <div className="text-red-400 text-xs">Missing download URL</div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Content */}
      <div className="p-4">
        {/* Video Title */}
        {isProcessing ? (
          <div className="my-3">
            <div className="w-3/4 h-5 bg-gradient-to-r from-gray-200 to-gray-300 rounded-lg animate-pulse mb-2 shadow-sm"></div>
            <div className="w-1/2 h-5 bg-gradient-to-r from-gray-200 to-gray-300 rounded-lg animate-pulse shadow-sm"></div>
          </div>
        ) : (
          <h3 className="text-[18px] font-medium text-[#171717] my-3 line-clamp-2">
            {video.title}
          </h3>
        )}

        {/* Buttons Container */}
        {isProcessing ? (
          <div className="flex gap-2">
            <div className="flex-1 py-[3px] px-4 rounded-full">
              <div className="w-full h-8 bg-gradient-to-r from-gray-200 to-gray-300 rounded-full animate-pulse shadow-sm border border-gray-200/50"></div>
            </div>
            <div className="flex-1 py-[3px] px-4 rounded-full">
              <div className="w-full h-8 bg-gradient-to-r from-gray-200 to-gray-300 rounded-full animate-pulse shadow-sm border border-gray-200/50"></div>
            </div>
          </div>
        ) : (
          <div className="flex gap-2">
            {!video.autoGenerated && (
              <button
                onClick={() => onPostVideo(video)}
                disabled={video.status !== 'ready'}
                className={`flex-1 py-[3px] px-4 rounded-full font-semibold text-[16px] transition-colors duration-300 flex items-center justify-center gap-2 group/btn cursor-pointer ${
                  video.status === 'ready'
                    ? 'bg-[#5046E5] text-white hover:bg-transparent hover:text-[#5046E5] border-2 border-[#5046E5]'
                    : 'bg-gray-300 text-gray-500 cursor-not-allowed border-2 border-gray-300'
                }`}
              >
                Post Video
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

